<a href="https://colab.research.google.com/github/swapna0727-source/AI/blob/main/data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/raw_customers.csv")

In [ ]:
df.head()

   customer_id  age   income    city plan_type  churned
0         2001   25  32000.0    Pune     Basic        1
1         2002   45      NaN   Delhi   Premium        0
2         2003   35  48000.0    Pune  Standard        1
3         2004   50  95000.0  Mumbai   Premium        0
4         2005   23      NaN   Delhi     Basic        1

In [ ]:
df.isnull().sum()

customer_id    0
age            0
income         8
city           0
plan_type      2
churned        0
dtype: int64

In [ ]:
df.dtypes

customer_id      int64
age              int64
income         float64
city            object
plan_type       object
churned          int64
dtype: object

In [ ]:
df['city'].value_counts()

city
Pune      10
Delhi     10
Mumbai    10
Name: count, dtype: int64

In [ ]:
df['plan_type'].value_counts()

plan_type
Basic       12
Premium      9
Standard     7
Name: count, dtype: int64

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [ ]:
df

    customer_id  age    income    city plan_type  churned
0          2001   25   32000.0    Pune     Basic        1
1          2002   45       NaN   Delhi   Premium        0
2          2003   35   48000.0    Pune  Standard        1
3          2004   50   95000.0  Mumbai   Premium        0
4          2005   23       NaN   Delhi     Basic        1
5          2006   41   72000.0  Mumbai  Standard        0
6          2007   33       NaN    Pune     Basic        1
7          2008   60  110000.0   Delhi   Premium        0
8          2009   29   29000.0  Mumbai     Basic        1
9          2010   54   89000.0    Pune   Premium        0
10         2011   31   45000.0   Delhi  Standard        0
11         2012   38       NaN  Mumbai     Basic        1
12         2013   47   91000.0    Pune   Premium        0
13         2014   27       NaN   Delhi     Basic        1
14         2015   44   76000.0  Mumbai  Standard        0
15         2016   36   43000.0    Pune       NaN        1
16         2017   52   93000.0   Delhi   Premium        0
17         2018   24   18000.0  Mumbai     Basic        1
18         2019   40       NaN    Pune  Standard        0
19         2020   32   36000.0   Delhi       NaN        1
20         2021   58   99000.0  Mumbai   Premium        0
21         2022   26   21000.0    Pune     Basic        1
22         2023   43   74000.0   Delhi  Standard        0
23         2024   34       NaN  Mumbai     Basic        1
24         2025   49   86000.0    Pune   Premium        0
25         2026   22   15000.0   Delhi     Basic        1
26         2027   39   67000.0  Mumbai  Standard        0
27         2028   30       NaN    Pune     Basic        1
28         2029   56   97000.0   Delhi   Premium        0
29         2030   28   20000.0  Mumbai     Basic        1

In [ ]:
df['income'].describe()

count        22.000000
mean      61636.363636
std       31363.529707
min       15000.000000
25%       33000.000000
50%       69500.000000
75%       90500.000000
max      110000.000000
Name: income, dtype: float64

In [ ]:
numeric_features=["income"]
numeric_pipeline=Pipeline(steps=[("imputer",SimpleImputer(strategy="median"))])

In [ ]:
type(numeric_pipeline)

sklearn.pipeline.Pipeline

In [ ]:
df

    customer_id  age    income    city plan_type  churned
0          2001   25   32000.0    Pune     Basic        1
1          2002   45       NaN   Delhi   Premium        0
2          2003   35   48000.0    Pune  Standard        1
3          2004   50   95000.0  Mumbai   Premium        0
4          2005   23       NaN   Delhi     Basic        1
5          2006   41   72000.0  Mumbai  Standard        0
6          2007   33       NaN    Pune     Basic        1
7          2008   60  110000.0   Delhi   Premium        0
8          2009   29   29000.0  Mumbai     Basic        1
9          2010   54   89000.0    Pune   Premium        0
10         2011   31   45000.0   Delhi  Standard        0
11         2012   38       NaN  Mumbai     Basic        1
12         2013   47   91000.0    Pune   Premium        0
13         2014   27       NaN   Delhi     Basic        1
14         2015   44   76000.0  Mumbai  Standard        0
15         2016   36   43000.0    Pune       NaN        1
16         2017   52   93000.0   Delhi   Premium        0
17         2018   24   18000.0  Mumbai     Basic        1
18         2019   40       NaN    Pune  Standard        0
19         2020   32   36000.0   Delhi       NaN        1
20         2021   58   99000.0  Mumbai   Premium        0
21         2022   26   21000.0    Pune     Basic        1
22         2023   43   74000.0   Delhi  Standard        0
23         2024   34       NaN  Mumbai     Basic        1
24         2025   49   86000.0    Pune   Premium        0
25         2026   22   15000.0   Delhi     Basic        1
26         2027   39   67000.0  Mumbai  Standard        0
27         2028   30       NaN    Pune     Basic        1
28         2029   56   97000.0   Delhi   Premium        0
29         2030   28   20000.0  Mumbai     Basic        1

In [ ]:
categorical_features=["city","plan_type"]

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
categorical_pipeline=Pipeline(steps=[
    ("imputer",SimpleImputer(strategy='most_frequent')),
    ("onehot",OneHotEncoder())])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
df

    customer_id  age    income    city plan_type  churned
0          2001   25   32000.0    Pune     Basic        1
1          2002   45       NaN   Delhi   Premium        0
2          2003   35   48000.0    Pune  Standard        1
3          2004   50   95000.0  Mumbai   Premium        0
4          2005   23       NaN   Delhi     Basic        1
5          2006   41   72000.0  Mumbai  Standard        0
6          2007   33       NaN    Pune     Basic        1
7          2008   60  110000.0   Delhi   Premium        0
8          2009   29   29000.0  Mumbai     Basic        1
9          2010   54   89000.0    Pune   Premium        0
10         2011   31   45000.0   Delhi  Standard        0
11         2012   38       NaN  Mumbai     Basic        1
12         2013   47   91000.0    Pune   Premium        0
13         2014   27       NaN   Delhi     Basic        1
14         2015   44   76000.0  Mumbai  Standard        0
15         2016   36   43000.0    Pune       NaN        1
16         2017   52   93000.0   Delhi   Premium        0
17         2018   24   18000.0  Mumbai     Basic        1
18         2019   40       NaN    Pune  Standard        0
19         2020   32   36000.0   Delhi       NaN        1
20         2021   58   99000.0  Mumbai   Premium        0
21         2022   26   21000.0    Pune     Basic        1
22         2023   43   74000.0   Delhi  Standard        0
23         2024   34       NaN  Mumbai     Basic        1
24         2025   49   86000.0    Pune   Premium        0
25         2026   22   15000.0   Delhi     Basic        1
26         2027   39   67000.0  Mumbai  Standard        0
27         2028   30       NaN    Pune     Basic        1
28         2029   56   97000.0   Delhi   Premium        0
29         2030   28   20000.0  Mumbai     Basic        1

In [ ]:
X=df[['age','income','city','plan_type']]
y=df['churned']

In [ ]:
X

    age    income    city plan_type
0    25   32000.0    Pune     Basic
1    45       NaN   Delhi   Premium
2    35   48000.0    Pune  Standard
3    50   95000.0  Mumbai   Premium
4    23       NaN   Delhi     Basic
5    41   72000.0  Mumbai  Standard
6    33       NaN    Pune     Basic
7    60  110000.0   Delhi   Premium
8    29   29000.0  Mumbai     Basic
9    54   89000.0    Pune   Premium
10   31   45000.0   Delhi  Standard
11   38       NaN  Mumbai     Basic
12   47   91000.0    Pune   Premium
13   27       NaN   Delhi     Basic
14   44   76000.0  Mumbai  Standard
15   36   43000.0    Pune       NaN
16   52   93000.0   Delhi   Premium
17   24   18000.0  Mumbai     Basic
18   40       NaN    Pune  Standard
19   32   36000.0   Delhi       NaN
20   58   99000.0  Mumbai   Premium
21   26   21000.0    Pune     Basic
22   43   74000.0   Delhi  Standard
23   34       NaN  Mumbai     Basic
24   49   86000.0    Pune   Premium
25   22   15000.0   Delhi     Basic
26   39   67000.0  Mumbai  Standard
27   30       NaN    Pune     Basic
28   56   97000.0   Delhi   Premium
29   28   20000.0  Mumbai     Basic

In [ ]:
y.value_counts()

churned
1    15
0    15
Name: count, dtype: int64

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=48,stratify=y)

In [ ]:
X_train

    age   income    city plan_type
12   47  91000.0    Pune   Premium
10   31  45000.0   Delhi  Standard
29   28  20000.0  Mumbai     Basic
26   39  67000.0  Mumbai  Standard
18   40      NaN    Pune  Standard
16   52  93000.0   Delhi   Premium
20   58  99000.0  Mumbai   Premium
4    23      NaN   Delhi     Basic
19   32  36000.0   Delhi       NaN
6    33      NaN    Pune     Basic
9    54  89000.0    Pune   Premium
11   38      NaN  Mumbai     Basic
17   24  18000.0  Mumbai     Basic
8    29  29000.0  Mumbai     Basic
22   43  74000.0   Delhi  Standard
14   44  76000.0  Mumbai  Standard
2    35  48000.0    Pune  Standard
5    41  72000.0  Mumbai  Standard
25   22  15000.0   Delhi     Basic
28   56  97000.0   Delhi   Premium
27   30      NaN    Pune     Basic
15   36  43000.0    Pune       NaN
21   26  21000.0    Pune     Basic
24   49  86000.0    Pune   Premium

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
preprocessor=ColumnTransformer(transformers=
                               [("numerical",numeric_pipeline,numeric_features),
                                 ("Categorical",categorical_pipeline,categorical_features)])

In [ ]:
preprocessor

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['income']),
                                ('Categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot', OneHotEncoder())]),
                                 ['city', 'plan_type'])])

In [ ]:
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['income']),
                                ('Categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot', OneHotEncoder())]),
                                 ['city', 'plan_type'])])

In [ ]:
X_train_transformed=preprocessor.transform(X_train)

In [ ]:
X_train

    age   income    city plan_type
12   47  91000.0    Pune   Premium
10   31  45000.0   Delhi  Standard
29   28  20000.0  Mumbai     Basic
26   39  67000.0  Mumbai  Standard
18   40      NaN    Pune  Standard
16   52  93000.0   Delhi   Premium
20   58  99000.0  Mumbai   Premium
4    23      NaN   Delhi     Basic
19   32  36000.0   Delhi       NaN
6    33      NaN    Pune     Basic
9    54  89000.0    Pune   Premium
11   38      NaN  Mumbai     Basic
17   24  18000.0  Mumbai     Basic
8    29  29000.0  Mumbai     Basic
22   43  74000.0   Delhi  Standard
14   44  76000.0  Mumbai  Standard
2    35  48000.0    Pune  Standard
5    41  72000.0  Mumbai  Standard
25   22  15000.0   Delhi     Basic
28   56  97000.0   Delhi   Premium
27   30      NaN    Pune     Basic
15   36  43000.0    Pune       NaN
21   26  21000.0    Pune     Basic
24   49  86000.0    Pune   Premium

In [ ]:
X_train_transformed

array([[9.1e+04, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00],
       [4.5e+04, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [2.0e+04, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [6.7e+04, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [6.7e+04, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [9.3e+04, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00],
       [9.9e+04, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00],
       [6.7e+04, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [3.6e+04, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [6.7e+04, 0.0e+00, 0.0e+00, 1.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [8.9e+04, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00],
       [6.7e+04, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [1.8e+04, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [2.9e+04, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [7.4e+04, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [7.6e+04, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [4.8e+04, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [7.2e+04, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [1.5e+04, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [9.7e+04, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00],
       [6.7e+04, 0.0e+00, 0.0e+00, 1.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [4.3e+04, 0.0e+00, 0.0e+00, 1.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [2.1e+04, 0.0e+00, 0.0e+00, 1.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [8.6e+04, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00]])

In [ ]:
X_train_transformed.shape

(24, 7)