<a href="https://colab.research.google.com/github/swapna0727-source/AI/blob/main/train_test_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_csv("/content/customers (1).csv")

In [ ]:
df.head()

   customer_id  age  monthly_spend  support_tickets  tenure_months  churned
0         1001   25           20.5                5              3        1
1         1002   45           80.0                0             28        0
2         1003   35           40.2                3             11        1
3         1004   50           95.5                0             36        0
4         1005   23           15.0                6              2        1

In [ ]:
df["churned"].value_counts()

churned
1    15
0    15
Name: count, dtype: int64

In [ ]:
X=df.drop(columns=['customer_id',"churned"])

In [ ]:
X.head()

   age  monthly_spend  support_tickets  tenure_months
0   25           20.5                5              3
1   45           80.0                0             28
2   35           40.2                3             11
3   50           95.5                0             36
4   23           15.0                6              2

In [ ]:
y=df['churned']

In [ ]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: churned, dtype: int64

In [ ]:
len((train_test_split(X,y,test_size=0.2)))

4

In [ ]:
type(train_test_split(X,y,test_size=0.2))

list

In [ ]:
train_test_split(X,y,test_size=0.2)[0].shape

(24, 4)

In [ ]:
train_test_split(X,y,test_size=0.2)[1].shape

(6, 4)

In [ ]:
type(train_test_split(X,y,test_size=0.2)[2])

pandas.core.series.Series

In [ ]:
train_test_split(X,y,test_size=0.2)[2].shape

(24,)

In [ ]:
train_test_split(X,y,test_size=0.2)[2]

25    1
4     1
14    0
16    0
24    0
15    1
9     0
8     1
7     0
23    1
6     1
21    1
12    0
20    0
26    0
29    1
17    1
10    0
2     1
27    1
5     0
0     1
11    1
19    1
Name: churned, dtype: int64

In [ ]:
train_test_split(X,y,test_size=0.2)[3].shape

(6,)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
X_train.index

Index([24,  0, 27, 13, 11,  7, 10, 14,  1, 19, 29,  6, 12, 23, 15, 16,  4, 17,
       28,  2,  5,  8,  3, 18],
      dtype='int64')

In [ ]:
X_train.index

Index([21,  2, 16, 10, 12, 28,  0, 14,  7, 24, 18, 20, 15, 13,  3, 11,  1,  9,
       29, 23, 19,  8,  4,  6],
      dtype='int64')

In [ ]:
X_train.index

Index([16, 21, 26, 25, 12, 18, 22, 28,  1, 27, 10,  3,  0, 19, 20,  5, 13,  8,
       14, 23, 17, 11,  6, 29],
      dtype='int64')

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=99999999)

In [ ]:
X_train.index

Index([25, 19, 18, 15, 11, 10, 20,  8, 26,  2,  1,  7,  5, 23,  9,  0, 29, 16,
       13,  6, 14, 12, 28, 17],
      dtype='int64')

In [ ]:
X_train.index

Index([25, 19, 18, 15, 11, 10, 20,  8, 26,  2,  1,  7,  5, 23,  9,  0, 29, 16,
       13,  6, 14, 12, 28, 17],
      dtype='int64')

In [ ]:
X_train.index

Index([25, 19, 18, 15, 11, 10, 20,  8, 26,  2,  1,  7,  5, 23,  9,  0, 29, 16,
       13,  6, 14, 12, 28, 17],
      dtype='int64')

In [ ]:
y_train.value_counts()

churned
1    12
0    12
Name: count, dtype: int64

In [ ]:
y_test.value_counts()

churned
1    3
0    3
Name: count, dtype: int64

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
y_train.value_counts()

churned
1    13
0    11
Name: count, dtype: int64

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1,stratify=y)

In [ ]:
y_train.value_counts()

churned
1    12
0    12
Name: count, dtype: int64